### ISSUE TITLE
"java.io.NotSerializableException" error

### ISSUE THREAD

**Issue by kyclark** [fangly/hitman#1]
When running "hitman_deploy," I am getting the error below.  Any suggestions?

Ken

```
[hpc:service0@/rsgrps/bhurwitz/hurwitzlab/tools/hitman/scripts]$ ./hitman_deploy --dir /rsgrps/bhurwitz/hurwitzlab/amplicon-illumina/03_hitman_deploy_out_kyc --input /rsgrps/bhurwitz/hurwitzlab/amplicon-illumina/02_hitman_hire_out_kyc/MockRun3hdrV4.R1.merge_pairs.assembled.MockRun3hdrV4.rename_seqs.cat_files.fastq -p SKIP_DENOISING=1 -p TRIM_LEN=250
====================================================================================================
|                              Starting Pipeline at 2016-06-08 14:34                               |
====================================================================================================

========================================= Stage seq_stats ==========================================
Exception in thread "Thread-8" java.io.NotSerializableException: bpipe.PipelineOutput
    at java.io.ObjectOutputStream.writeObject0(Unknown Source)
    at java.io.ObjectOutputStream.writeObject(Unknown Source)
```

**Comment by fangly** [comment]
Hello Ken,
Does the fastq output file produced by the previous hitman_hire step look
good? Were there any warnings in the hire or deploy steps?
Did you previously run the complete hitman workflow successfully or is it
your first time? If it is, it may be bad software versions. Bpipe used to
not work with the latest java version, for example.
Best,
Florent
